spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneCounter
    username: postgres
    password: wecare4U
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: mapper/*.xml